package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"regexp"
	"syscall"
	"time"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

var (
	tracer        trace.Tracer
	logger        *slog.Logger
	validIDRegex   = regexp.MustCompile(`^[a-zA-Z0-9_-]{1,64}$`)
	validFaultTypeRegex = regexp.MustCompile(`^[a-zA-Z0-9_-]{1,64}$`)
)

func init() {
	logger = slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelInfo}))
	tracer = otel.Tracer("orchestrator-service")
}

// ─────────────────────────────────────────────
// Request / Response models
// ─────────────────────────────────────────────

type ProvisionRequest struct {
	UserID string `json:"user_id"`
	Level  int    `json:"level"`
}

type ProvisionResponse struct {
	ClusterID string `json:"cluster_id"`
	Status    string `json:"status"`
	Message   string `json:"message,omitempty"`
}

type InjectFaultRequest struct {
	ClusterID string `json:"cluster_id"`
	FaultType string `json:"fault_type"`
}

type InjectFaultResponse struct {
	ClusterID string `json:"cluster_id"`
	FaultType string `json:"fault_type"`
	Status    string `json:"status"`
}

type HealthResponse struct {
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
	Version   string `json:"version"`
}

type ErrorResponse struct {
	Error   string `json:"error"`
	Details string `json:"details,omitempty"`
}

// ─────────────────────────────────────────────
// Validation helpers
// ─────────────────────────────────────────────

func validateProvisionRequest(req *ProvisionRequest) error {
	if req.UserID == "" {
		return errors.New("user_id is required")
	}
	if !validIDRegex.MatchString(req.UserID) {
		return errors.New("user_id contains invalid characters")
	}
	if req.Level < 1 || req.Level > 5 {
		return errors.New("level must be between 1 and 5")
	}
	return nil
}

func validateInjectFaultRequest(req *InjectFaultRequest) error {
	if req.ClusterID == "" {
		return errors.New("cluster_id is required")
	}
	// cluster_id is generated by this service as "vcluster-<user_id>", e.g. "vcluster-U12345"
	if !validIDRegex.MatchString(req.ClusterID) {
		return errors.New("cluster_id contains invalid characters")
	}
	if req.FaultType == "" {
		return errors.New("fault_type is required")
	}
	if !validFaultTypeRegex.MatchString(req.FaultType) {
		return errors.New("fault_type contains invalid characters")
	}
	return nil
}

// ─────────────────────────────────────────────
// Response helpers
// ─────────────────────────────────────────────

func writeJSON(w http.ResponseWriter, status int, payload any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if err := json.NewEncoder(w).Encode(payload); err != nil {
		logger.Error("failed to encode response", "error", err)
	}
}

func writeError(w http.ResponseWriter, status int, msg string) {
	writeJSON(w, status, ErrorResponse{Error: msg})
}

// ─────────────────────────────────────────────
// Handlers
// ─────────────────────────────────────────────

// HealthHandler returns service health and readiness status.
func HealthHandler(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, HealthResponse{
		Status:    "ok",
		Timestamp: time.Now().UTC().Format(time.RFC3339),
		Version:   os.Getenv("APP_VERSION"),
	})
}

// ProvisionClusterHandler deploys an ephemeral vcluster for the given user.
func ProvisionClusterHandler(w http.ResponseWriter, r *http.Request) {
	ctx, span := tracer.Start(r.Context(), "ProvisionCluster")
	defer span.End()

	if r.Method != http.MethodPost {
		writeError(w, http.StatusMethodNotAllowed, "method not allowed")
		return
	}

	var req ProvisionRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		span.SetStatus(codes.Error, "invalid request body")
		writeError(w, http.StatusBadRequest, "invalid request body")
		return
	}

	if err := validateProvisionRequest(&req); err != nil {
		span.SetStatus(codes.Error, err.Error())
		writeError(w, http.StatusUnprocessableEntity, err.Error())
		return
	}

	span.SetAttributes(
		attribute.String("user.id", req.UserID),
		attribute.Int("simulation.level", req.Level),
	)

	clusterID, err := provisionVCluster(ctx, req.UserID, req.Level)
	if err != nil {
		logger.ErrorContext(ctx, "cluster provisioning failed", "user_id", req.UserID, "error", err)
		span.SetStatus(codes.Error, err.Error())
		writeError(w, http.StatusInternalServerError, "cluster provisioning failed")
		return
	}

	logger.InfoContext(ctx, "cluster provisioned", "user_id", req.UserID, "cluster_id", clusterID, "level", req.Level)
	writeJSON(w, http.StatusAccepted, ProvisionResponse{
		ClusterID: clusterID,
		Status:    "provisioning",
		Message:   fmt.Sprintf("Ephemeral cluster for user %s is being provisioned", req.UserID),
	})
}

// InjectFaultHandler injects a specific misconfiguration into an active cluster.
func InjectFaultHandler(w http.ResponseWriter, r *http.Request) {
	ctx, span := tracer.Start(r.Context(), "InjectFault")
	defer span.End()

	if r.Method != http.MethodPost {
		writeError(w, http.StatusMethodNotAllowed, "method not allowed")
		return
	}

	var req InjectFaultRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		span.SetStatus(codes.Error, "invalid request body")
		writeError(w, http.StatusBadRequest, "invalid request body")
		return
	}

	if err := validateInjectFaultRequest(&req); err != nil {
		span.SetStatus(codes.Error, err.Error())
		writeError(w, http.StatusUnprocessableEntity, err.Error())
		return
	}

	span.SetAttributes(
		attribute.String("cluster.id", req.ClusterID),
		attribute.String("fault.type", req.FaultType),
	)

	if err := injectFault(ctx, req.ClusterID, req.FaultType); err != nil {
		logger.ErrorContext(ctx, "fault injection failed", "cluster_id", req.ClusterID, "fault_type", req.FaultType, "error", err)
		span.SetStatus(codes.Error, err.Error())
		writeError(w, http.StatusInternalServerError, "fault injection failed")
		return
	}

	logger.InfoContext(ctx, "fault injected", "cluster_id", req.ClusterID, "fault_type", req.FaultType)
	writeJSON(w, http.StatusOK, InjectFaultResponse{
		ClusterID: req.ClusterID,
		FaultType: req.FaultType,
		Status:    "injected",
	})
}

// ─────────────────────────────────────────────
// K8s / vcluster integration stubs
// (replace with client-go calls in production)
// ─────────────────────────────────────────────

func provisionVCluster(ctx context.Context, userID string, level int) (string, error) {
	// TODO: Use client-go / Helm SDK to deploy a Loft vcluster dynamically.
	// The cluster name is deterministic to allow idempotent reprovisioning.
	clusterID := fmt.Sprintf("vcluster-%s", userID)
	logger.InfoContext(ctx, "provisioning vcluster (stub)", "cluster_id", clusterID, "level", level)
	return clusterID, nil
}

func injectFault(ctx context.Context, clusterID, faultType string) error {
	// TODO: Apply the appropriate K8s manifest inside the target vcluster to
	// simulate the requested misconfiguration (e.g., broken RBAC, missing
	// NetworkPolicy, invalid ResourceQuota).
	logger.InfoContext(ctx, "injecting fault (stub)", "cluster_id", clusterID, "fault_type", faultType)
	return nil
}

// ─────────────────────────────────────────────
// Middleware
// ─────────────────────────────────────────────

func loggingMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()
		next.ServeHTTP(w, r)
		logger.Info("request",
			"method", r.Method,
			"path", r.URL.Path,
			"remote_addr", r.RemoteAddr,
			"duration_ms", time.Since(start).Milliseconds(),
		)
	})
}

// ─────────────────────────────────────────────
// Bootstrap
// ─────────────────────────────────────────────

func newRouter() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("/healthz", HealthHandler)
	mux.HandleFunc("/api/v1/cluster/provision", ProvisionClusterHandler)
	mux.HandleFunc("/api/v1/cluster/inject-fault", InjectFaultHandler)
	return loggingMiddleware(mux)
}

func main() {
	// OpenTelemetry tracer (already initialized via init())
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	srv := &http.Server{
		Addr:         ":" + port,
		Handler:      newRouter(),
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 30 * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	// Graceful shutdown
	idleConnsClosed := make(chan struct{})
	go func() {
		quit := make(chan os.Signal, 1)
		signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
		<-quit
		logger.Info("shutting down gracefully…")
		ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()
		if err := srv.Shutdown(ctx); err != nil {
			logger.Error("server forced to shutdown", "error", err)
		}
		close(idleConnsClosed)
	}()

	logger.Info("orchestrator starting", "port", port)
	if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
		logger.Error("server error", "error", err)
		os.Exit(1)
	}
	<-idleConnsClosed
}
